### ISSUE TITLE
Doesn't work with React-Router 5.0.0

### ISSUE THREAD

**Issue by jens-duttke** [ipatate/react-router-scroll-memory#18]
After updating to react-router 5.0.0, I get the following error, if I use the `ScrollMemory` component as described in the documentation:
```
Uncaught Invariant Violation: You should not use <Route> or withRouter() outside a <Router>
    at invariant (http://127.0.0.1:8080/help-center/js/vendor.min.js:11126:15)
    at Route.computeMatch (http://127.0.0.1:8080/help-center/js/vendor.min.js:43168:53)
    at Route.computeMatch (http://127.0.0.1:8080/help-center/js/vendor.min.js:39119:25)
    at new Route (http://127.0.0.1:8080/help-center/js/vendor.min.js:43143:20)
    at new Route (eval at ES6ProxyComponentFactory (http://127.0.0.1:8080/help-center/js/vendor.min.js:38737:10), <anonymous>:5:7)
    at constructClassInstance (http://127.0.0.1:8080/help-center/js/vendor.min.js:28493:18)
    at updateClassComponent (http://127.0.0.1:8080/help-center/js/vendor.min.js:31819:5)
    at beginWork (http://127.0.0.1:8080/help-center/js/vendor.min.js:32776:16)
    at performUnitOfWork (http://127.0.0.1:8080/help-center/js/vendor.min.js:36444:12)
    at workLoop (http://127.0.0.1:8080/help-center/js/vendor.min.js:36484:24)
```

```
The above error occurred in the <Route> component:
    in Route (created by withRouter(o))
    in withRouter(o) (created by Main)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Main)
    in Main (created by App)
    in I18NLoader (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
```

It looks like, it's not allowed anymore to place non-`Route`/`Switch` components into the `BrowserRouter`-component.

**Comment by ipatate** [comment]
Sorry, i look this when i can.

**Comment by seleckis** [comment]
I have the same issue, what is a workaround?
